# syntax=docker/dockerfile:1.4

FROM --platform=$BUILDPLATFORM node:22-bullseye-slim as build

RUN mkdir -p /project
WORKDIR /project

COPY ./package.json package.json
COPY ./package-lock.json package-lock.json

RUN npm ci

COPY . .

RUN npm run build --prod

FROM nginx:stable-alpine

RUN mkdir -p /project
WORKDIR /project

RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /project/dist/comicvault_frontend/browser /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
